# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-13 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_api', '0002_auto_20180513_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsinfo',
            name='validity',
            field=models.BooleanField(default=False),
        ),
    ]
