# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_api', '0003_auto_20180513_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsinfo',
            name='sent_date',
            field=models.DateTimeField(),
        ),
    ]
